//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaWebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int MesajId { get; set; }
        public string Adres { get; set; }
        public Nullable<int> UyeId { get; set; }
        public Nullable<int> PizzaId { get; set; }
        public Nullable<int> Telefon { get; set; }
    
        public virtual Pizza Pizza { get; set; }
        public virtual Uye Uye { get; set; }
    }
}
