//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dil {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzaWebProje.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Bu türü kesin olarak belirtilmiş kaynak sınıfını kullanarak geçerli iş parçacığının
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Admin Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminanasayfa {
            get {
                return ResourceManager.GetString("adminanasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Paneli benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminpaneli {
            get {
                return ResourceManager.GetString("adminpaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Admin Panelinden Çık benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adminpanelindencik {
            get {
                return ResourceManager.GetString("adminpanelindencik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad Soyad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string adsoyad {
            get {
                return ResourceManager.GetString("adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Anasayfa benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çıkış benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string cikis {
            get {
                return ResourceManager.GetString("cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Düzenle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string duzenle {
            get {
                return ResourceManager.GetString("duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ekle {
            get {
                return ResourceManager.GetString("ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiyat benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fiyat {
            get {
                return ResourceManager.GetString("fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fotoğraf benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string fotograf {
            get {
                return ResourceManager.GetString("fotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri Dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string geridon {
            get {
                return ResourceManager.GetString("geridon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string hakkinda {
            get {
                return ResourceManager.GetString("hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İletişim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string iletisim {
            get {
                return ResourceManager.GetString("iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bu işlemi gerçekleştirmek istediğinize emin misiniz ? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string islemonayi {
            get {
                return ResourceManager.GetString("islemonayi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kaydet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kayitol {
            get {
                return ResourceManager.GetString("kayitol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string kullaniciadi {
            get {
                return ResourceManager.GetString("kullaniciadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mesaj benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mesaj {
            get {
                return ResourceManager.GetString("mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Fotoğraf benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string mevcutfotograf {
            get {
                return ResourceManager.GetString("mevcutfotograf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PİZZA benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pizza {
            get {
                return ResourceManager.GetString("pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pizza Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pizzaadi {
            get {
                return ResourceManager.GetString("pizzaadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pizza Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pizzaekle {
            get {
                return ResourceManager.GetString("pizzaekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PİZZALAR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pizzalar {
            get {
                return ResourceManager.GetString("pizzalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pizza Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string pizzasil {
            get {
                return ResourceManager.GetString("pizzasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SATIN AL benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string satinal {
            get {
                return ResourceManager.GetString("satinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string sil {
            get {
                return ResourceManager.GetString("sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Üye Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string uyeol {
            get {
                return ResourceManager.GetString("uyeol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Pizza Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string yenipizzaekle {
            get {
                return ResourceManager.GetString("yenipizzaekle", resourceCulture);
            }
        }
    }
}
